#!/usr/bin/env php
<?php
set_time_limit(0);

require_once __DIR__ . '/vendor/autoload.php';
$app = require_once __DIR__ . "/src/app.php";

$console = &$app["console"];
$console->add(new \GoRemote\Cli\CheckSourceCommand());
$console->add(new \GoRemote\Cli\SendDailyDigestCommand());
$console->run();